###############################################################################
############                     MODULES ARROWS                    ############
###############################################################################

[module/arrow1]
; grey to Blue
type = custom/text
content = "%{T2} %{T-}"
content-font = 2
content-foreground = #8d62a9
content-background = #292d3e

[module/arrow2]
; grey to Blue
type = custom/text
content = "%{T2} %{T-}"
content-font = 2
content-foreground = #668bd7
content-background = #8d62a9

[module/arrow3]
; grey to Blue
type = custom/text
content = "%{T2} %{T-}"
content-font = 2
content-foreground = #8b62a9
content-background = #668bd7
