[module/date]
;https://github.com/jaagr/polybar/wiki/Module:-date
type = internal/date
; Seconds to sleep between updates
interval = 5
; See "http://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
date = " %a %b %d, %Y"
date-alt = " %a %b %d, %Y"
time = %H:%M
time-alt = %l:%M%p
format-prefix = "📅 "
format-prefix-foreground = ${colors.color4}
format-foreground = ${colors.color4}
format-background = ${colors.background}
format-underline = ${colors.color4}
format-margin = 2
format-padding = 0
label = "%date% %time% "


;date = %H:%M
;date-alt = %Y-%m-%d %H:%M:%S
;
;label = %date%
;label-foreground = ${colors.primary}
