;[module/xkeyboard]
;;https://github.com/jaagr/polybar/wiki/Module:-xkeyboard
;type = internal/xkeyboard
;blacklist-0 = num lock
;
;format-prefix = " "
;format-prefix-foreground = ${colors.foreground}
;format-prefix-background = ${colors.background}
;format-prefix-underline = #3ecfb2
;format-foreground = ${colors.foreground}
;format-background = ${colors.background}
;
;label-layout = %layout%
;label-layout-underline = #3ecfb2
;label-indicator-padding = 2
;label-indicator-margin = 1
;label-indicator-background = ${colors.background}
;label-indicator-underline = ${colors.foreground}
;;label-layout-foreground = ${colors.primary}
;;label-indicator-background = ${colors.secondary}
;
;
;[module/xmenu]
;type = custom/script
;interval = 1200
;exec = echo "  "
;click-left = "sh ~/xmenu/xmenu.sh"
;format-foreground = ${colors.foreground}
;format-background = ${colors.background}


[module/xwindow]
;https://github.com/jaagr/polybar/wiki/Module:-xwindow
type = internal/xwindow

; Available tokens:
;   %title%
; Default: %title%
label = %title:0:60:...%
label-maxlen = 50

format-prefix = "*  "
format-suffix = "  *"
format-foreground = ${colors.color10}
format-background = ${colors.background}
format-margin = 2
format-padding = 0

;[module/xbacklight]
;;https://github.com/jaagr/polybar/wiki/Module:-xbacklight
;type = internal/xbacklight
;format = <label> <bar>
;format-prefix = "   "
;format-prefix-foreground = ${colors.foreground}
;format-prefix-background = ${colors.background}
;format-prefix-underline = #9f78e1
;format-underline = #9f78e1
;label = %percentage%%
;bar-width = 10
;bar-indicator = 
;bar-indicator-foreground = #fff
;bar-indicator-font = 2
;bar-fill = 
;bar-fill-font = 2
;bar-fill-foreground = #9f78e1
;bar-empty = 
;bar-empty-font = 2
;bar-empty-foreground = #fff
;format-foreground = ${colors.foreground}
;format-background = ${colors.background}
;
;[module/xworkspaces]
;type = internal/xworkspaces
;
;label-active = %name%
;label-active-background = ${colors.background-alt}
;label-active-underline= ${colors.primary}
;label-active-padding = 1
;
;label-occupied = %name%
;label-occupied-padding = 1
;
;label-urgent = %name%
;label-urgent-background = ${colors.alert}
;label-urgent-padding = 1
;
;label-empty = %name%
;label-empty-foreground = ${colors.disabled}
;label-empty-padding = 1
