[module/memory1]
;https://github.com/jaagr/polybar/wiki/Module:-memory
type = internal/memory
interval = 1
; Available tokens:
;   %percentage_used% (default)
;   %percentage_free%
;   %gb_used%
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
label = %percentage_used%%
label-active-font = 2
bar-used-indicator =
bar-used-width = 10
bar-used-foreground-0 = #3384d0
bar-used-fill = 
bar-used-empty = 
bar-used-empty-foreground = #ffffff

format = <label> <bar-used>
format-prefix = "  "
format-prefix-foreground = #3384d0
format-underline = #4B5665
format-foreground = ${colors.foreground}
format-background = ${colors.background}

[module/memory2]
;https://github.com/jaagr/polybar/wiki/Module:-memory
type = internal/memory
interval = 1
; Available tokens:
;   %percentage_used% (default)
;   %percentage_free%
;   %gb_used%
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
label = %percentage_used%%
label-active-font = 2

format = Mem <label>
format-prefix = "💾 "
format-prefix-foreground = ${colors.color11}
format-foreground = ${colors.color11}
format-background = ${colors.background}
format-underline = ${colors.color11}
format-margin = 2
format-padding = 0

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%
