[module/uptime]
;https://github.com/jaagr/polybar/wiki/User-contributed-modules#uptime
type = custom/script
exec = uptime | awk -F, '{sub(".*up ",x,$1);print $1}'
interval = 100
label = Uptime : %output%

format-foreground = ${colors.color13}
format-background = ${colors.background}
format-prefix = "💻 "
format-prefix-foreground = ${colors.color13}
format-underline = ${colors.color13}
format-margin = 2
format-padding = 0

[module/release]
type = custom/script
exec = lsb_release -d | awk {'print $2'} ;echo " "; lsb_release -r | awk {'print $2'}) | tr -d '\n'
interval = 6000

format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-prefix = "  "
format-prefix-foreground = #62FF00
format-underline = #62FF00


[module/load-average]
type = custom/script
exec = uptime | grep -ohe 'load average[s:][: ].*' | awk '{ print $3" "$4" "$5"," }' | sed 's/,//g'
interval = 100

;HOW TO SET IT MINIMAL 10 CHARACTERS - HIDDEN BEHIND SYSTEM ICONS
;label = %output%
label = %output:10%
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-prefix = "  "
format-prefix-foreground = #62FF00
format-underline = #62FF00

[module/kernel]
type = custom/script
exec = uname -r
tail = false
interval = 1024
format-prefix = " 🤖 "
format-prefix-foreground = ${colors.color2}
format-foreground = ${colors.color2}
format-background = ${colors.background}
format-underline = ${colors.color2}
format-margin = 2
format-padding = 0
