;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[global/wm]
margin-top = 0
margin-bottom = 0

[settings]
screenchange-reload = true
compositing-background = over
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over


; Define fallback values used by all module formats
format-foreground = #FF0000
format-background = #00FF00
;format-underline =
;format-overline =
format-spacing = 3
;format-padding =
;format-margin =
;format-offset =

[colors]
; To change color scheme, change the COLOR-SCHEME value inside ${COLOR-SCHEME.colorXX}.
; Each colorscheme is defined in file with appropriate name in colorschemes directory.

background = ${Nord.background}
foreground = ${Nord.foreground}
color0     = ${Nord.color0}
color1     = ${Nord.color1}
color2     = ${Nord.color2}
color3     = ${Nord.color3}
color4     = ${Nord.color4}
color5     = ${Nord.color5}
color6     = ${Nord.color6}
color7     = ${Nord.color7}
color8     = ${Nord.color8}
color9     = ${Nord.color9}
color10    = ${Nord.color10}
color11    = ${Nord.color11}
color12    = ${Nord.color12}
color13    = ${Nord.color13}
color14    = ${Nord.color14}
color15    = ${Nord.color15}
alert      = ${Nord.color1}

;; Include directory with colorschemes
include-directory = colorschemes
include-directory = modules

;################################################################################
;############                  MAINBAR-HERBST                        ############
;################################################################################

[bar/mainbar-herbst]
monitor = ${env:MONITOR}
monitor-strict = true
width = 100%
height = 2%
radius = 0.0
fixed-center = true
bottom = false
separator =

dpi = {xrdb:Xft.dpi:96}
;dpi= 192

background = ${Nord.background}
foreground = ${Nord.foreground}

line-size = 2
line-color = #f00


; Enable support for inter-process messaging
; See the Messaging wiki page for more details.
enable-ipc = true

border-size = 0
;border-left-size = 0
;border-right-size = 25
;border-top-size = 0
;border-bottom-size = 25
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin-left = 0
module-margin-right = 0


font-0 = "Ubuntu:style=Bold:size=11;2"
font-1 = "UbuntuMono Nerd Font:style=Bold:size=18;3"
font-2 = "Font Awesome 6 Free:style=Regular:pixelsize=11;1"
font-3 = "Font Awesome 6 Free:style=Solid:pixelsize=11;1"
font-4 = "Font Awesome 6 Brands:pixelsize=8;1"
font-5 = "Noto Color Emoji:size=11;1"

modules-left = ewmh xwindow
modules-center =
;modules-right = arrow1 networkspeedup networkspeeddown arrow2 memory2 arrow3 cpu2 arrow2 volume arrow3 arch-aur-updates arrow2 date
;modules-right = memory2 cpu2 battery date
modules-right = battery date
;modules-right = memory2 cpu2 volume date


scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

;################################################################################
;############                  MAINBAR-XMONAD                        ############
;################################################################################

[bar/mainbar-xmonad]
monitor = ${env:MONITOR}
;monitor-fallback = HDMI1
monitor-strict = false
override-redirect = false
wm-restack = generic
width = 100%
height = 22
;offset-x = 1%
;offset-y = 1%
radius = 0.0
fixed-center = true
bottom = false
separator =

background = ${Nord.background}
foreground = ${Nord.foreground}

line-size = 2
line-color = #f00

;border-size = 2
;border-left-size = 25
;border-right-size = 25
;border-top-size = 0
;border-bottom-size = 25
border-color = #00000000

padding-left = 0
; padding-right adds padding between 'date' and the edge of screen and/or systray.
padding-right = 1

; Enable support for inter-process messaging
; See the Messaging wiki page for more details.
enable-ipc = true

font-0 = "Ubuntu:style=Bold:size=9;2"
font-1 = "UbuntuMono Nerd Font:style=Bold:size=18;3"
font-2 = "Font Awesome 6 Free:style=Regular:pixelsize=8;1"
font-3 = "Font Awesome 6 Free:style=Solid:pixelsize=8;1"
font-4 = "Font Awesome 6 Brands:pixelsize=8;1"

modules-left = ewmh xwindow
modules-center =
modules-right = kernel cpu2 memory2 filesystem uptime volume date

tray-detached = false
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 2
tray-maxsize = 20
tray-scale = 1.0
tray-position = right
tray-background = ${colors.background}


;################################################################################
;############                  MAINBAR-DEFAULT                       ############
;################################################################################

[bar/default]
monitor = ${env:MONITOR}
width = 100%
height = 1.5%

fixed-center = true
bottom = false
radius = 6
;dpi = {xrdb:Xft.dpi}
dpi= 196

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000


padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = monospace;2

modules-left = xworkspaces xwindow
modules-right = filesystem pulseaudio xkeyboard memory cpu wlan eth date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

; vim:ft=dosini
