#!/run/current-system/profile/bin/bash

WALLPAPER='/home/kovalev/Pictures/japan-city-anime.jpg'
ENABLE_PICOM=true

hc attr theme.tiling.reset 1 ?
hc attr theme.floating.reset 1 ?
hc set frame_border_active_color '#222222cc'
hc set frame_border_normal_color '#101010cc'
hc set frame_bg_normal_color '#ffffffff'
hc set frame_bg_active_color '#ff007fd0'
#hc set frame_border_width 0
hc set frame_border_width 1
hc set frame_bg_transparent on
hc set frame_normal_opacity 35
hc set frame_transparent_width 3
hc set frame_gap 0


hc attr theme.title_height 0
hc attr theme.title_font 'Dejavu Sans:pixelsize=12'  # example using Xft
hc attr theme.padding_top 0  # space below the title's baseline (i.e. text depth)

hc set window_gap 10
hc set frame_padding 0
hc set show_frame_decorations none
hc set smart_window_surroundings off
hc set smart_frame_surroundings hide_all
hc set mouse_recenter_gap 0

hc attr theme.border_width 2
hc attr theme.inner_width 1
hc attr theme.outer_width 0
#hc attr theme.active.color '#15f4eed0'
hc attr theme.active.color '#d9596bd0'
#hc attr theme.active.color '#8fa5bdd0'
#hc attr theme.active.inner_color '#15f4eed0'
hc attr theme.active.inner_color '#d9596bd0'
#hc attr theme.active.inner_color '#8fa5bdd0'
hc attr theme.urgent.color '#fff01f'
hc attr theme.urgent.inner_color '#fff01f'
hc attr theme.normal.color '#00000000'
hc attr theme.normal.inner_color '#00000000'
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.background_color '#141414'


#set wallpaper with feh
feh --no-fehbg --bg-scale $WALLPAPER


#turn on picom
if $ENABLE_PICOM; then
    picom --backend glx -b
fi
